FROM elasticsearch:7.6.1

MAINTAINER hnliuwx@gmail.com

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b  https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.6.1/elasticsearch-analysis-ik-7.6.1.zip
