base:
  upload-dir: /kykms/KmDocs
  db-backup-dir: /kykms/dbBackup
  soffice-path: /usr/bin/soffice
esclient:
  master-host: kykms-ES-comm
  master-port: 9200
  master-auth: false
spring:
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://kykms-mysql-comm:3306/km?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 3
    host: kykms-redis-comm
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: 123456
    port: 6379
jeecg:
  uploadType: local
  path :
    upload: /opt/upload
    webapp: /opt/webapp
  oss:
    accessKey: ??
    secretKey: ??
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: ??
    staticDomain: https://static.jeecg.com
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
